scrape_configs:
  - job_name: "heart-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["heart-api:8000"]

  - job_name: "mlflow"
    metrics_path: /metrics
    static_configs:
      - targets: ["mlflow:5000"]