apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-api
spec:
  replicas: 2   # production-grade (HA)
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
        - name: heart-api
          image: ghcr.io/raju55/heart-api:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "production"
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
