apiVersion: v1
kind: Service
metadata:
  name: heart-api-svc
  namespace: heart-mlops
spec:
  type: NodePort
  selector:
    app: heart-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
